### PR TITLE
Add missing ds4drv setup

### PR DESCRIPTION
**Pull request by Tiryoh**
## Proposed change(s)

Add missing ds4drv setup procedure

### Types of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which refactor the code)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update only
- [ ] Other (please describe)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/mangdangroboticsclub/mini_pupper/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

## Test Configuration

__Raspberry Pi OS version__  
Ubuntu 22.04

### CODE REVIEW

**Comment by hdumcke** [comment]
I think there are a few fundamental decision we have to take before making these changes:

1) I suggest to drop ROS1 completely. We do not have resources to support ROS1 and ROS2 but more importantly ROS1 requires Ubuntu 20.04 and cloud-init on Ubuntu 20.04 does not support the prepare_sd installation procedure. This might be fixable but I do not want to spend time on something I want to get rid of

2) I suggest that we move all setup scripts from this repo to the actual repo of the application we want to install

3) Generic joystick support is in mini_pupper_ros_bsp (and in Stanford repo if we do not use ROS) ds4drv is installed in mini_pupper_ros_bsp/install.sh but wrongly where the camera is installed and it lacks the dev rules

For now I will add your changes to  mini_pupper_ros_bsp/install.sh and we make a decision on 1 and 2

I see the mini_pupper repo as mainly a documentation repo and prepare_sd is added as a convenience to have a single point of entry to install all the different SW stacks on mini pupper

**Comment by Tiryoh** [comment]
I have no objection to drop support for ROS 1 for Mini Pupper 2, I was not able to fully test the combination on Mini Pupper 2+ROS 1, so I removed it from the pull request.

> I suggest that we move all setup scripts from this repo to the actual repo of the application we want to install

I think this discussion is independent of the topic on whether this pull request should be incorporated or not.
It is OK to future maintenance in a separate repository. However, I do not believe that this is a reason to stop fixing (not adding new features) currently published scripts.

**Comment by hdumcke** [comment]
You are right, let's merge and fix later

**Comment by hdumcke** [comment]
Changes are now included in mini_pupper_ros_bsp/setup.sh

We can close this PR without merging

**Pull request closed without merging**
